### ISSUE TITLE
Allow OrderLine and ChargeLine to be extensible

### ISSUE THREAD

**Issue by anbereza** [st-tu-dresden/salespoint#340]
This issue was raised during the final presentation this year's software engineering lab and @martinmo suggested I open an issue on it here.

There are two big points:

1. It should be possible to extend the OrderLine (and maybe ChargeLine) class/classes by making their constructors public. 
2. It should be possible to access OrderLine and ChargeLine objects directly from an Order and to update them.

The use case for 1. would be a scenario in which we need to manage the state of individual OrderLines after having created an Order. Such an OrderLine would be a pizza that is going through different states during the lifecycle of an Order. The list of ingredients of such a pizza (as a String) is another thing that we would want to attach to an OrderLine. 

For 2. we would like to easily access OrderLine and ChargeLine objects to display detailed information about each Order and to make changes to these objects through the Order. Right now, the Order class only lets us retrieve very basic information about what the Order actually contains apart from being able to get a total for all the attached OrderLines and ChargeLines.

**Comment by odrotbohm** [comment]
Thanks for filing this. Before I follow up with a few questions, some fundamentals. Neither `OrderLine` nor `ChargeLine` are designed to be extended in the first place. The non-exposure of the constructors is part of that. Both `…Line` abstractions are effectively implementation details of `Order`, most importantly the relationship between products and the `…Line` abstractions. Another indicator of that is that the `…Line` types are effectively immutable in the API they expose. Fundamentally, that's why the generic `add(…)` methods were deprecated in Salespoint 7.0 in the first place.

> It should be possible to extend the OrderLine (and maybe ChargeLine) class/classes by making their constructors public.

Adding the constructor wouldn't help much as you'd have to register the `…Line` instances with the repository. That in turn would require the calling code know about the internals of how `Order` manages those instances which fundamentally subverts the idea of an aggregate in the first place.

> Such an OrderLine would be a pizza that is going through different states during the lifecycle of an Order.

Can you elaborate on that?

> The list of ingredients of such a pizza (as a String) is another thing that we would want to attach to an OrderLine.

Orders know about `AttachedChargeLine` instances, which are essentially `ChargeLines` attached to an `OrderLine` wouldn't you be able to add the ingredients via those (e.g. a base product "Pizza Margherita") plus toppings like ham, extra cheese etc added as `ACL` via `….addChargeLine(price, "Ham", pizza)`?

**Comment by DerKolibri** [comment]
> > Such an OrderLine would be a pizza that is going through different states during the lifecycle of an Order.
> 
> Can you elaborate on that?

In our project, employees create orders for customers of a pizzaservice. When an order with a pizza is created, then that pizza starts in the IN_PREPARATION state and the OrderStatus is OPEN. Later, an employee would prepare that pizza for the oven and set it to PREPARED. Then a scheduled method (oven) sets it to BAKING. With the next call of the scheduled method, it gets set to DONE. If all pizzas contained in an Order are DONE, then it can be set to IN_DELIVERY. In the last step of the order lifecycle it gets set to DELIVERED. The OrderStatus is set to PAID and then COMPLETED.

> > The list of ingredients of such a pizza (as a String) is another thing that we would want to attach to an OrderLine.
> 
> Orders know about `AttachedChargeLine` instances, which are essentially `ChargeLines` attached to an `OrderLine` wouldn't you be able to add the ingredients via those (e.g. a base product "Pizza Margherita") plus toppings like ham, extra cheese etc added as `ACL` via `….addChargeLine(price, "Ham", pizza)`?

Yes, that's possible, but how would I then retrieve information about those `AttachedChargeLine` instances for an `OrderLine` from an `Order` if I wanted to display that information?

**Comment by odrotbohm** [comment]
> In our project, employees create orders for customers of a pizzaservice. When an order with a pizza is created, then that pizza starts in the IN_PREPARATION state and the OrderStatus is OPEN. Later, an employee would prepare that pizza for the oven and set it to PREPARED. Then a scheduled method (oven) sets it to BAKING. With the next call of the scheduled method, it gets set to DONE. If all pizzas contained in an Order are DONE, then it can be set to IN_DELIVERY. In the last step of the order lifecycle it gets set to DELIVERED. The OrderStatus is set to PAID and then COMPLETED.

I think the fundamental misassumption here is that the lifecycle of the pizza should be implemented "within" the order. The pizza to be prepared can be (and IMO should be) modeled completely independent and only keep a reference to its original order / order line. State changes in the pizza can then be propagated to the order, taking its state forward based on your domain rules. Effectively consider the Order an *inbound* description of what needs to prepared and a certain set of actual pizzas to be prepared and delivered eventually derived from that.

> Yes, that's possible, but how would I then retrieve information about those AttachedChargeLine instances for an OrderLine from an Order if I wanted to display that information?

```java
order.getOrderLines().forEach(orderLine -> {
  order.getChargeLines(orderLine).forEach(attachedChargeLine -> { … });
});
```

**Comment by DerKolibri** [comment]
I see, that definitely sounds like a good solution to the problems we faced when we were working under that missassumption and I think I understand the reasoning now. With that being said, I think this issue can be closed then.
