### ISSUE TITLE
`OrderManagement.completeOrder(…)` still returns completed `Order` on failure

### ISSUE THREAD

**Issue by Deric-W** [st-tu-dresden/salespoint#409]
An Exception is thrown if `OrderManagement.completeOrder` fails because there is not enough stock to complete the order.
To my surprise is `Order.isCompleted()`  equal to `true` after the failed call, which is not what I expected it to.
Interestingly, the change seems not to be stored and can be reversed with `order = this.orders.get(order.getId()).get();`.

Maybe related to #23?

**Comment by odrotbohm** [comment]
Unfortunately, JPA, the persistence mechanism leaves instances in the state to be modified, even if the transaction rolls back due to an exception. This means, that quite generally, you have to assume entities to be in an undefined state when an exception occurs and reload them through corresponding APIs, just as you already do.

I'll add a note to the Javadoc of `OrderManagement.completeOrder(…)` to warn about this.

**Comment by odrotbohm** [comment]
I've found a way to work around the problem that's not particularly elegant, but should work for our purposes.
